### ISSUE TITLE
Tracking the last sent data on the receiver

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#6]
- [x] Whenever the receiver receives data from sender and successfully processes the data, they will record the lastRecordId received in a SQLite table `p2p_received_history`.

- [x] The table `p2p_received_history` will have the columns
                 - device_id (String)
                 - type (Enum)
                 - last_record_id (Bigint)

- [x] `device_id` will identify the device the data was received from

- [x] `type` will identify the type of data that was received e.g Clients,Events,Tasks,Locations,Structures,etc

- [x] `last_record_id` will identify the last record received from the device and of type

- [x]  This table cannot be  synced from server and must be created only during P2P Sync
