### ISSUE TITLE
Negotiating start of data exchange

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#8]
- [x] Whenever authentication and authorization are completed, the sending app will send  its [hash key](https://github.com/OpenSRP/opensrp-client-p2p/issues/5).

- [x] The receiver will in turn return the details of the last receipt from the sender. This data will be the lastRecordId per type of Data. 

- [x] The receiver will query the SQLite table [`p2p_hash_keys`](https://github.com/OpenSRP/opensrp-client-p2p/issues/6) using the sender device ID. 

- [x] If the hash key is found  and matches the stored key, then the receiver sends the sending history from the SQLite `p2p_received_history` 

- [x] If the hash key is found on local database but does not match the one stored then the records in [p2p_received_history](https://github.com/OpenSRP/opensrp-client-p2p/issues/6) for the sender are deleted.  The receiver returns a null or empty object meaning no records were previously sent and all records should be sent

- [x]  if the hash key was not found, the receiver returns a null object or or empty object  meaning no records were previously sent and all records should be sent
